contact_links:
  - name: ğŸ’¡ Discussions - Ideas
    url: https://github.com/RubberDuckCrew/gitdone/discussions/categories/ideas
    about: Feel free to share ideas for the project that are to vague to create a dedicated issue beforehand
  - name: â‰ Discussions - Q&A
    url: https://github.com/RubberDuckCrew/gitdone/discussions/categories/q-a
    about: Please ask questions here
  - name: ğŸ—¨ Discussions - General
    url: https://github.com/RubberDuckCrew/gitdone/discussions/categories/general
    about: Discuss more general topics here
