name: Enforce conventions

on:
  pull_request_target:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  enforce-labels:
    name: Enforce pull request labels
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Enforce pull request labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "^(?!(âš—ï¸ Request Build$|ğŸ’¬ Discussion$|â“ Question$|âŒ Wontfix$|ğŸ”„ Duplicate$|ğŸš§ Work in Progress$)).+" # Exclude meta labels (do not describe PR content)
          use_regex: true
          add_comment: true
          message: "ğŸ·ï¸ Please assign at least one label to this pull request before requesting a review. See our [contributing conventions](https://rubberduckcrew.pages.dev/contributing/conventions) for details."

  enforce-branch-names:
    name: Enforce pull request branch names
    runs-on: ubuntu-latest

    steps:
      - name: Enforce pull request branch names
        uses: IamPekka058/branchMatchRegex@v2
        with:
          path: https://raw.githubusercontent.com/RubberDuckCrew/.github/refs/heads/main/configs/conventions/branches.yml
          useWildcardPatterns: true
